POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Initial Test",
  "author": "Brandon Lim",
  "url": "facebook.com/william",
  "likes": "21",
  "user": "606ace60a232c2ad1a14daf6"
}